### ISSUE TITLE
Question about aux_dataloader

### ISSUE THREAD

**Issue by LoveMiki** [zjgans/dcan#2]
I do not know why you close the issues, so i open a new issue for the question.

Could you explain the purpose of generating img2, img3, and img4 in aux_dataloader.py? It seems that you are enlarging the image pool of dataloader for later data sampling. And in the train.py, every time you only choose data_aux[0] for training. Why do not use data_aux[1] or data_aux[2] or data_aux[3]?

**Comment by zjgans** [comment]
Because img[0] adopts the general data augmentation strategies used in few-shot learning (FSL), such as randomhorizontalflip and color jitter, while img[1], img[2] and img[3] require more complex  transformations to each image. I just wanted to list more options for data augmentation, but it doesn't affect the running of the code. I hope you can get a deeper insight into FSL by reading more papers, such as ProtoNet,DeepMind,FEAT,RFS,PAL,IE,DeepBDC,etc.

**Comment by LoveMiki** [comment]
I just wonder why unnecessary transformations are implemented in your code and actually there is no FSL paper called DeepMind but only DeepEMD, please check before you are giving some unnecessary suggestions to someone.

**Comment by zjgans** [comment]
Thank you for your suggestion.
